// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrQidfFqXZs-Ug35WcYY3Fp2nnJ2r26As',
    appId: '1:617761177457:web:a8db812ec06e8d9c2480d0',
    messagingSenderId: '617761177457',
    projectId: 'reportplus-77914',
    authDomain: 'reportplus-77914.firebaseapp.com',
    storageBucket: 'reportplus-77914.firebasestorage.app',
    measurementId: 'G-31XN1BKQGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCG8Bqh1BflaBYTTFiFlYSnMltVYPCAlw',
    appId: '1:617761177457:android:3bdf1ab06bb2da3b2480d0',
    messagingSenderId: '617761177457',
    projectId: 'reportplus-77914',
    storageBucket: 'reportplus-77914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzNz2cRg8YJcYdXXcAqcT-vNY_zF3X1EU',
    appId: '1:617761177457:ios:64639838cb626ffd2480d0',
    messagingSenderId: '617761177457',
    projectId: 'reportplus-77914',
    storageBucket: 'reportplus-77914.firebasestorage.app',
    iosBundleId: 'com.example.appf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzNz2cRg8YJcYdXXcAqcT-vNY_zF3X1EU',
    appId: '1:617761177457:ios:64639838cb626ffd2480d0',
    messagingSenderId: '617761177457',
    projectId: 'reportplus-77914',
    storageBucket: 'reportplus-77914.firebasestorage.app',
    iosBundleId: 'com.example.appf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrQidfFqXZs-Ug35WcYY3Fp2nnJ2r26As',
    appId: '1:617761177457:web:df667fc0868b81c82480d0',
    messagingSenderId: '617761177457',
    projectId: 'reportplus-77914',
    authDomain: 'reportplus-77914.firebaseapp.com',
    storageBucket: 'reportplus-77914.firebasestorage.app',
    measurementId: 'G-4764QJWVL0',
  );
}
